Packer base
Otus-DevOps-2018-02/Chichavl_infra pull request #5
Opened 2018-03-26 11:29 UTC by Chichavl

# Выполнено ДЗ № 6

 - [X] Основное ДЗ
 - [X] Задание со *

## В процессе сделано:
 - Созданы packer скрипты для семейств reddit-base и reddit-full
 - Написан Unit для systemd для автостарта сервера puma
 - Добавлен скрипт с командой создания экземпляра семейства reddit-full

## Как запустить проект:
 - В директории `config-scripts` выполнить `create-reddit-vm.sh`

## Как проверить работоспособность:
 - Перейти по ссылке `http://EXTERNAL_IP:9292`, должна открыться главная страница Reddit App

## PR checklisk
 - [X] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2018-04-01 12:52 UTC, sedovandrew requested changes
Подправь, пожалуйста, замечания. В остальном всё выполнено здорово. Задания со звёздочкой увидел.

2018-04-01 12:52 UTC, sedovandrew commented on config-scripts/create-reddit-vm.sh
> +gcloud compute instances create reddit-fill \
По правилам хорошего тона вначале скрипта пишется shebang - `#!/bin/bash`

2018-04-01 12:52 UTC, sedovandrew commented on packer/files/run.sh
> +mv /home/appuser/puma.service /etc/systemd/system/
Здесь тоже бы поставить shebang.

2018-04-01 12:52 UTC, sedovandrew commented on packer/immutable.json
> +            "source": "files/daemon.sh",
Не нашёл файл `packer/files/daemon.sh` в проекте.

2018-04-01 22:18 UTC, Chichavl commented on packer/immutable.json
> +            "source": "files/daemon.sh",
Удалил его коммитом https://github.com/Otus-DevOps-2018-02/Chichavl_infra/pull/5/commits/4ac350ea9cfdc12cb5085a9506e363a96d3a554a, из файла уберу.

2018-04-02 02:45 UTC, sedovandrew approved these changes

2018-04-02 02:46 UTC, sedovandrew commented
ДЗ засчитано. Сливай в мастер ветку.

2018-04-02 11:21 UTC, merged