Terraform 1
Otus-DevOps-2018-02/Chichavl_infra pull request #6
Opened 2018-04-01 03:35 UTC by Chichavl

# Выполнено ДЗ №

 - [X] Основное ДЗ
 - [X] Задание со *

## В процессе сделано:
 - Создан хост с приложением при помощи terraform
 - Добавлены ключи ssh в проект при помощи terraform
 - Создан балансировщик и 2 экземпляра приложения при помощи terraform

## Как запустить проект:
 - запустить команду `terraform apply` в директории `terraform`

## Как проверить работоспособность:
 - Перейти по ссылке http://%lb_external_ip%

## PR checklisk
 - [X] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2018-04-01 19:41 UTC, Nklya commented
Почему коммиты в репозиторий идут от 2 разных пользователей???

<img width="445" alt="screen shot 2018-04-01 at 22 40 42" src="https://user-images.githubusercontent.com/26086394/38176779-bda615b4-35fd-11e8-9214-395ab2251ba5.png">

2018-04-01 22:02 UTC, Chichavl commented
Это всего один коммит - на локальной windows машине не смог делать последние задания, переехал к себе на linux dedicated, там был настроен глобально рабочий аккаунт гита, когда заметил переправил на уровне репозитория эл. почту.

2018-04-02 04:31 UTC, Nklya commented
Ок, хорошо.

2018-04-04 13:45 UTC, Nklya requested changes
Добрый день.

Вадим, условия ДЗ относительно выполнены, но вот реализация не очень.

Нужно вычистить отсюда простыни публичных ключей и передавать их по-нормальному через параметры.
Плюс, параметр count нужно вынести в переменные.

2018-04-04 13:45 UTC, Nklya commented on terraform/main.tf
> +    count = 2
count должен быть в variables.

2018-04-04 13:45 UTC, Nklya commented on terraform/outputs.tf
> +  value = "${google_compute_instance.app.0.network_interface.0.access_config.0.assigned_nat_ip}"
Если мы используем count, то зачем нам две переменные для вывода значений?
Достаточно `value = "${google_compute_instance.app.*.network_interface.0.access_config.0.assigned_nat_ip}"`

2018-04-04 13:45 UTC, Nklya commented on README.md
> +resource "google_compute_project_metadata_item" "default" {
Хардкодить простыни ключей в код это очень, очень плохое решение.

2018-04-04 13:45 UTC, Nklya commented on terraform/main.tf
> +#resource "google_compute_project_metadata_item" "default" {
Не обязательно хранить этот пример здесь в виде коммента.

2018-04-04 13:45 UTC, Nklya commented on terraform/main.tf
> +        ssh-keys = "appuser:${file(var.public_key_path)}"
Почему здесь ты нормально используешь путь к публичному ключу?

2018-04-04 13:45 UTC, Nklya commented on terraform/main.tf
> +  value = "appuser1:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPidPiD0QVEH/SPgcTwdaPVbxniLQznseoDh33tk7dOKF31cl4+nQ7tAo/XEkAPQg82qYT6O4RyMJxzAgBokCv0kp+w9g7kZG/Pb8+fTi8/hSczn0+rN93VG4/LIkth0DLzSkhIBCZge1
А здесь генерируешь простыни из того же самого?

2018-04-18 10:00 UTC, Nklya approved these changes
Добрый день.

Вадим, условия ДЗ выполнены, выглядит все относительно ок 👍

2018-04-18 10:00 UTC, Nklya commented on terraform/variables.tf
> +  default     = "appuser1:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPidPiD0QVEH/SPgcTwdaPVbxniLQznseoDh33tk7dOKF31cl4+nQ7tAo/XEkAPQg82qYT6O4RyMJxzAgBokCv0kp+w9g7kZG/Pb8+fTi8/hSczn0+rN93VG4/LIkth0DLzSkhI
Ну вот зачем здесь эта простыня, если можно нормально объединять переменные?
Например https://github.com/Otus-DevOps-2018-02/SergeSpinoza_infra/blob/terraform-1/terraform/main.tf#L9

2018-04-18 10:33 UTC, merged

2018-04-18 10:34 UTC, Nklya commented
смержено для проверки дальше