Terraform 2
Otus-DevOps-2018-02/Chichavl_infra pull request #7
Opened 2018-04-15 19:58 UTC by Chichavl

# Выполнено ДЗ № 8

 - [X] Основное ДЗ
 - [X] Задание со *

## В процессе сделано:
 - Вынесли создание машин в модули, использовали эти модули для создания разных окружений
 - Попробовали работать с модулем storage-bucket из реестра модулей
 - Попробовали работать с remote backends
 - Разнесено приложение и бд на разные серевера при помощи provisioner

## Как запустить проект:
 - запустить команду `terraform apply` в директории `terraform/stage`

## Как проверить работоспособность:
 - Перейти по ссылке http://%lb_external_ip%

## PR checklisk
 - [X] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2018-04-16 15:21 UTC, Nklya commented
Сейчас тревис падает потому что:
- В packer/ubuntu16.json и packer/db.json должна быть последняя пустая строка
- Файл terraform/prod/terraform.tfvars.example должен быть

2018-04-16 23:30 UTC, Chichavl commented
Все поправил. Не успел вчера, хотел очередь занять на проверку, а тут вон как быстро))

2018-04-17 09:15 UTC, Nklya requested changes
Ревью этого PR будет произведено после фикса предыдущего

2018-04-18 11:09 UTC, Nklya approved these changes
Добрый день.

Вадим, условия ДЗ выполнены, все выглядит относительно ок 👍 

В этом PR или в следующем нужно вычистить мусор из репы в виде .swp файлов.
Плюс, вcе *.bak перенести в в trerraform/old

Комментарии ниже.

2018-04-18 11:09 UTC, Nklya commented on terraform/app.tf.bak
> +resource "google_compute_instance" "app" {
Зачем генерить пачку .bak файлов, если можно было их нормально сложить в terraform/old  например?

2018-04-18 11:09 UTC, Nklya commented on terraform/terraform.tfvars.bak
> +project = "infra-197910"
Этот файл здесь зачем?

2018-04-18 11:09 UTC, Nklya commented on terraform/modules/app/files/puma.service.tpl
> +ExecStart=/bin/bash -lc 'DATABASE_URL=${db_ip} puma'
Переменные окружения лучше передавать в системд юнитах через директиву Environment 
https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html

2018-04-18 11:10 UTC, Nklya commented on terraform/backend.tf
> +terraform {
Настройка удаленного бекенда для этого кода имеет мало смысла.
Основная инфра разворачивается из terraform/stage, prod.

2018-04-24 15:05 UTC, merged